#!/bin/python3
import numpy as np
import matplotlib.pyplot as plt
import time
import sounddevice as sd

fs = 44100
seconds = 1024/fs

line1 = []

start = time.time()

while time.time() - start < 60:
    data = sd.rec(int(seconds * fs), samplerate=fs, channels=1)
    sd.wait()
    data = data.reshape((1024))
    sp = np.fft.rfft(data)
    freq = np.fft.rfftfreq(data.shape[0],d=1/fs)

    sp = np.abs(sp)
    sp = sp[(30 <= freq)]
    freq = freq[(30 <= freq)]

    if line1 == []:
        plt.ion()
        fig = plt.figure()
        ax = fig.add_subplot(111)
        line1, = ax.plot(freq,sp)
        plt.show()

    plt.xscale("log")
    plt.ylim([0,500])
    line1.set_ydata(sp)
    plt.pause(0.05)

plt.show()
